### PR TITLE
Suggestion for the test script

### PR DESCRIPTION
**Pull request by andleb**

### CODE REVIEW

**Comment by andleb** [comment]
Hi, instead of writing code in Slack, I thought it would be more helpful to create a pull request.
This small fix now works on my machine if I have only *.Rmd present.

**Comment by OmerRonen** [comment]
Hi @andleb , 
thanks for the suggestion,
could you please show your directory and error.
It seems to work for me:
Screen Shot 2021-08-29 at 16 15 28

**Comment by andleb** [comment]
Hi!
This:
Screenshot from 2021-08-29 16-19-55
Results in this:
Screenshot from 2021-08-29 16-20-55
On the latest commit in the main repo (I branched it as "old").

**Comment by andleb** [comment]
I should add that I'm on Linux with the bash shell.

**Review by OmerRonen — APPROVED** [review]
@andleb thanks!

**Pull request merged**
